export const AgreementConstants = {
    termsHash: "Terms hash",
    termsDescription: "The term hash is the fingerprint of the associated agreement document file. It is uniquely generated by an algorithm using the number of bits in the file. It is used to verify that the file is the same file that was used to create the agreement and that it has not been modified." 
}