export { default as Body1 } from "./Body1";
export { default as Body2 } from "./Body2";
export { default as Body3 } from "./Body3";
export { default as BodyHeadline } from "./BodyHeadline";
export { default as Headline1 } from "./Headline1";
export { default as Headline2 } from "./Headline2";
export { default as Headline3 } from "./Headline3";
export { default as Headline4 } from "./Headline4";
export { default as HeadlineBasic } from "./HeadlineBasic";