name: Smart Contracts CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [16.x]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./packages/contracts
    steps:
      - uses: actions/checkout@v3
      - uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - run: echo $(forge --version)
      - run: forge install
      - run: forge build
      - run: forge test
      - run: forge coverage
      - run: forge coverage --report lcov
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./packages/contracts
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./packages/contracts/yarn.lock"
      - run: npm install yarn
      - run: npx yarn install
      - run: npx yarn lint:check
